name: Status tracking

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Check status
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        TELEGRAM_CHAT_ID: "-1001463677498;-1001287849567"
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      run: |
        docker build -t tracker:latest .
        docker run -v ${{ github.workspace }}:/app -e USERNAME=$USERNAME -e PASSWORD=$PASSWORD -e GITHUB_REPOSITORY=$GITHUB_REPOSITORY -e TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID -e TELEGRAM_TOKEN=$TELEGRAM_TOKEN tracker:latest
        git config --global user.email "github@pixelexperience.org"
        git config --global user.name "PixelExperience"
        git add .
        changed=$(git diff --numstat --cached | wc -l)
        if [[ "$changed" -eq 0 ]]; then
        echo "State of status remains same as of previous check. Exiting"
        exit 0
        fi
        git commit -m "Sync: $(date)"
        git push
